const data = new Date();
console.log('dia:', data.getDate());
console.log('mês:', data.getMonth()+1);
console.log('ano:', data.getFullYear());
console.log('hora:', data.getHours());
console.log('min:', data.getMinutes());
console.log('seg:', data.getSeconds());
console.log('ms:', data.getMilliseconds());
console.log('Dia da semana:', data.getDay());
console.log(data.toString());